-- horizontal movement
-- f( -> jumps to first instance of '('
-- t( -> jumps to character just before '('
-- ; -> repeat the search to jump to next instance of '('
-- F( -> same as f( but jumps backwards
-- df) -> deletes everything inside plus (...)
-- dt) -> deletes everything inside (...)
-- yt( -> yanks upto first '('

  -- vertical movement
  -- * -> searches for the word that the cursor is on
  -- # -> same as above but upwards
